import { v4 as uuidv4 } from 'uuid';

export const worldCupContests = [
  // Official FIFA & Coca-Cola
  {
    title: 'Coca-Cola FIFA World Cup 2026 Match Day Getaway',
    description: 'Win all-expense paid trip to World Cup match',
    organization: 'Coca-Cola',
    prizeDescription: 'Round-trip flights, hotel, match tickets, meals',
    estimatedValue: '20000',
    amoeMethod: 'No purchase required - mail-in entry form or online',
    physicalRequirements: 'Mail postcard to Coca-Cola Sweepstakes address with entry form',
    endDate: new Date('2026-11-30'),
    source: 'Coca-Cola Official',
  },
  {
    title: 'Coca-Cola Sam\'s Club World Cup Sweepstakes',
    description: 'Weekly World Cup prizes and grand prize trip',
    organization: 'Coca-Cola x Sam\'s Club',
    prizeDescription: 'Weekly merchandise, grand prize World Cup VIP package',
    estimatedValue: '15000',
    amoeMethod: 'Mail-in AMOE entry without purchase',
    physicalRequirements: 'Mail entry form to Sam\'s Club address',
    endDate: new Date('2026-10-31'),
    source: 'Sam\'s Club Official',
  },
  {
    title: 'Coca-Cola Match Ball Contest',
    description: 'Enter to win signed World Cup match ball',
    organization: 'Coca-Cola',
    prizeDescription: 'Official signed World Cup match ball, merchandise',
    estimatedValue: '5000',
    amoeMethod: 'Online or mail-in entry',
    physicalRequirements: 'Optional mail entry to Coca-Cola',
    endDate: new Date('2026-11-15'),
    source: 'Coca-Cola Official',
  },

  // Unilever Partners
  {
    title: 'Unilever Target World Cup Promotion',
    description: 'Enter to win World Cup experiences at Target',
    organization: 'Unilever x Target',
    prizeDescription: 'World Cup merchandise packages, gift cards, experiences',
    estimatedValue: '2000',
    amoeMethod: 'No purchase required online entry',
    physicalRequirements: 'None - online entry only',
    endDate: new Date('2026-10-15'),
    source: 'Target Official',
  },
  {
    title: 'Unilever Walmart World Cup Sweepstakes',
    description: 'Win World Cup gear and experiences',
    organization: 'Unilever x Walmart',
    prizeDescription: 'World Cup merchandise, Walmart gift cards',
    estimatedValue: '3000',
    amoeMethod: 'Online AMOE form',
    physicalRequirements: 'None',
    endDate: new Date('2026-10-20'),
    source: 'Walmart Official',
  },
  {
    title: 'Unilever Walgreens World Cup Contest',
    description: 'Enter at Walgreens for World Cup prizes',
    organization: 'Unilever x Walgreens',
    prizeDescription: 'Health/beauty products, World Cup merchandise',
    estimatedValue: '1500',
    amoeMethod: 'In-store or online no-purchase entry',
    physicalRequirements: 'None',
    endDate: new Date('2026-09-30'),
    source: 'Walgreens Official',
  },

  // Airlines & Travel
  {
    title: 'American Airlines FIFA World Cup Final Party at EDGE',
    description: 'Win VIP experience at exclusive World Cup party',
    organization: 'American Airlines',
    prizeDescription: 'VIP party tickets, airfare, hotel, meals',
    estimatedValue: '8000',
    amoeMethod: 'Mail-in entry form required',
    physicalRequirements: 'Mail completed entry to American Airlines address',
    endDate: new Date('2026-11-01'),
    source: 'American Airlines Official',
  },
  {
    title: 'Verizon FIFA World Cup Golden Tickets',
    description: 'Win World Cup match tickets through Verizon',
    organization: 'Verizon',
    prizeDescription: 'Match tickets, VIP experiences, merchandise',
    estimatedValue: '10000',
    amoeMethod: 'Free account registration (no purchase needed)',
    physicalRequirements: 'None',
    endDate: new Date('2026-11-20'),
    source: 'Verizon Official',
  },
  {
    title: 'Marriott Bonvoy World Cup Sleepover Suite',
    description: 'Win luxury hotel stay during World Cup',
    organization: 'Marriott Bonvoy',
    prizeDescription: 'Luxury hotel suite, match tickets, meals',
    estimatedValue: '12000',
    amoeMethod: 'Online entry no purchase required',
    physicalRequirements: 'None',
    endDate: new Date('2026-10-30'),
    source: 'Marriott Official',
  },

  // Major Sponsors
  {
    title: 'Adidas x Champs Sports World Cup Sweepstakes',
    description: 'Win official Adidas World Cup gear',
    organization: 'Adidas x Champs Sports',
    prizeDescription: 'Official Adidas World Cup apparel and equipment',
    estimatedValue: '2500',
    amoeMethod: 'No purchase entry online',
    physicalRequirements: 'None',
    endDate: new Date('2026-10-10'),
    source: 'Champs Sports Official',
  },
  {
    title: 'Nike World Cup 2026 Sweepstakes',
    description: 'Win limited edition Nike World Cup collection',
    organization: 'Nike',
    prizeDescription: 'Exclusive Nike World Cup apparel and shoes',
    estimatedValue: '1500',
    amoeMethod: 'Online no-purchase entry',
    physicalRequirements: 'None',
    endDate: new Date('2026-09-15'),
    source: 'Nike Official',
  },
  {
    title: 'McDonald\'s World Cup 2026 Sweepstakes',
    description: 'World Cup prizes with McDonald\'s purchases',
    organization: 'McDonald\'s',
    prizeDescription: 'Free meals, merchandise, trip to World Cup',
    estimatedValue: '5000',
    amoeMethod: 'Mail-in AMOE entry without purchase',
    physicalRequirements: 'Mail entry form to McDonald\'s',
    endDate: new Date('2026-11-10'),
    source: 'McDonald\'s Official',
  },
  {
    title: 'Lay\'s World Cup Gear Up for the Final Match',
    description: 'Win World Cup prizes from Lay\'s',
    organization: 'Lay\'s (Pepsi Co)',
    prizeDescription: 'World Cup merchandise, experiences, money',
    estimatedValue: '3000',
    amoeMethod: 'No-purchase online entry',
    physicalRequirements: 'None',
    endDate: new Date('2026-10-31'),
    source: 'Lay\'s Official',
  },
  {
    title: 'Budweiser 40th Anniversary World Cup Collectible',
    description: 'Win limited edition collectible Budweiser packs',
    organization: 'Budweiser',
    prizeDescription: 'Limited edition collectible 40th anniversary packs',
    estimatedValue: '500',
    amoeMethod: 'Mail-in or online entry',
    physicalRequirements: 'Optional mail entry',
    endDate: new Date('2026-09-30'),
    source: 'Budweiser Official',
  },
  {
    title: 'Casamigos World Cup Sweepstakes',
    description: 'Win Casamigos tequila and World Cup experience',
    organization: 'Casamigos',
    prizeDescription: 'Tequila bottles, World Cup experience package',
    estimatedValue: '4000',
    amoeMethod: 'Mail-in entry (no purchase required)',
    physicalRequirements: 'Mail entry to Casamigos address',
    endDate: new Date('2026-10-15'),
    source: 'Casamigos Official',
  },
  {
    title: 'Dr. Squatch World Cup Sweepstakes',
    description: 'Win Dr. Squatch products and World Cup gear',
    organization: 'Dr. Squatch',
    prizeDescription: 'Soap products, World Cup merchandise',
    estimatedValue: '800',
    amoeMethod: 'Online no-purchase entry',
    physicalRequirements: 'None',
    endDate: new Date('2026-09-30'),
    source: 'Dr. Squatch Official',
  },
  {
    title: 'POWERADE FIFA Match Tickets',
    description: 'Win World Cup match tickets from POWERADE',
    organization: 'POWERADE (Coca-Cola)',
    prizeDescription: 'World Cup match tickets, travel packages',
    estimatedValue: '8000',
    amoeMethod: 'Email entry or mail-in',
    physicalRequirements: 'Mail postcard to POWERADE address',
    endDate: new Date('2026-10-20'),
    source: 'POWERADE Official',
  },
  {
    title: 'Valvoline For the Driven World Cup National Sweeps',
    description: 'Win World Cup prizes from Valvoline',
    organization: 'Valvoline',
    prizeDescription: 'World Cup merchandise, oil changes, cash',
    estimatedValue: '2000',
    amoeMethod: 'Online AMOE form (no purchase needed)',
    physicalRequirements: 'None',
    endDate: new Date('2026-10-31'),
    source: 'Valvoline Official',
  },

  // Automotive
  {
    title: 'Kia FIFA World Cup 2026 Sweepstakes',
    description: 'Win Kia vehicles and World Cup experiences',
    organization: 'Kia Motors',
    prizeDescription: 'Kia vehicle, World Cup VIP package',
    estimatedValue: '50000',
    amoeMethod: 'Mail-in entry without vehicle purchase',
    physicalRequirements: 'Mail entry form to Kia address',
    endDate: new Date('2026-11-30'),
    source: 'Kia Official',
  },
  {
    title: 'Toyota World Cup Sweepstakes',
    description: 'Win Toyota vehicle and World Cup trip',
    organization: 'Toyota',
    prizeDescription: 'Toyota vehicle, match tickets, travel',
    estimatedValue: '40000',
    amoeMethod: 'Mail-in AMOE entry',
    physicalRequirements: 'Mail entry to Toyota address',
    endDate: new Date('2026-11-15'),
    source: 'Toyota Official',
  },
  {
    title: 'Ford World Cup Vehicle Giveaway',
    description: 'Win Ford vehicle plus World Cup experience',
    organization: 'Ford Motor',
    prizeDescription: 'Ford vehicle, World Cup VIP package',
    estimatedValue: '45000',
    amoeMethod: 'Online or mail-in entry (no purchase required)',
    physicalRequirements: 'Optional mail entry',
    endDate: new Date('2026-11-01'),
    source: 'Ford Official',
  },

  // Retail
  {
    title: 'Best Buy & Hisense World Cup Sweepstakes',
    description: 'Win Hisense TV and World Cup content',
    organization: 'Best Buy x Hisense',
    prizeDescription: 'Hisense smart TV, World Cup streaming packages',
    estimatedValue: '3000',
    amoeMethod: 'Mail-in entry without purchase',
    physicalRequirements: 'Mail entry form to Best Buy address',
    endDate: new Date('2026-10-31'),
    source: 'Best Buy Official',
  },
  {
    title: 'Sports Authority World Cup Gear Contest',
    description: 'Win World Cup sports equipment and apparel',
    organization: 'Sports Authority',
    prizeDescription: 'Soccer balls, cleats, jerseys, equipment',
    estimatedValue: '2000',
    amoeMethod: 'Online no-purchase entry',
    physicalRequirements: 'None',
    endDate: new Date('2026-10-15'),
    source: 'Sports Authority Official',
  },
  {
    title: 'Dick\'s Sporting Goods World Cup Sweepstakes',
    description: 'Win sporting goods and World Cup experiences',
    organization: 'Dick\'s Sporting Goods',
    prizeDescription: 'Sporting equipment, gift cards, experiences',
    estimatedValue: '2500',
    amoeMethod: 'No-purchase online entry',
    physicalRequirements: 'None',
    endDate: new Date('2026-10-20'),
    source: 'Dick\'s Sporting Goods Official',
  },

  // Media & Entertainment
  {
    title: 'FOX Super 6 World Cup Bracket Challenge',
    description: '$1M prize pool for World Cup predictions',
    organization: 'FOX Sports',
    prizeDescription: 'Cash prizes up to $1,000,000, weekly drawings',
    estimatedValue: '100000',
    amoeMethod: 'Free online bracket (no purchase needed)',
    physicalRequirements: 'None',
    endDate: new Date('2026-12-18'),
    source: 'FOX Sports Official',
  },
  {
    title: 'ESPN World Cup Prediction Games',
    description: 'Compete in ESPN fantasy World Cup games',
    organization: 'ESPN',
    prizeDescription: 'Prize pool varies, merchandise, cash',
    estimatedValue: '10000',
    amoeMethod: 'Free online entry',
    physicalRequirements: 'None',
    endDate: new Date('2026-12-15'),
    source: 'ESPN Official',
  },
  {
    title: 'DoorDash FIFA World Cup Ticket Sweepstakes',
    description: 'Win World Cup tickets through DoorDash',
    organization: 'DoorDash',
    prizeDescription: 'World Cup match tickets, travel, DoorDash credits',
    estimatedValue: '7000',
    amoeMethod: 'Free account entry (no meal purchase required)',
    physicalRequirements: 'None',
    endDate: new Date('2026-11-10'),
    source: 'DoorDash Official',
  },

  // Financial Services
  {
    title: 'Bank of America Visa World Cup Hospitality',
    description: 'BofA cardholders chance to win World Cup VIP package',
    organization: 'Bank of America x Visa',
    prizeDescription: 'VIP hospitality package, flights, hotels, matches',
    estimatedValue: '15000',
    amoeMethod: 'Mail-in entry without credit card required',
    physicalRequirements: 'Mail entry to BofA address',
    endDate: new Date('2026-11-30'),
    source: 'Bank of America Official',
  },
  {
    title: 'Chase World Cup Rewards',
    description: 'Earn World Cup tickets through Chase rewards',
    organization: 'Chase Bank',
    prizeDescription: 'World Cup match tickets, merchandise',
    estimatedValue: '8000',
    amoeMethod: 'Mail-in or online entry (no card needed)',
    physicalRequirements: 'Optional mail entry',
    endDate: new Date('2026-11-15'),
    source: 'Chase Official',
  },
  {
    title: 'Capital One World Cup Sweepstakes',
    description: 'Win World Cup experiences from Capital One',
    organization: 'Capital One',
    prizeDescription: 'World Cup trip for 2, match tickets',
    estimatedValue: '12000',
    amoeMethod: 'Online no-purchase entry',
    physicalRequirements: 'None',
    endDate: new Date('2026-10-31'),
    source: 'Capital One Official',
  },

  // Cryptocurrency
  {
    title: 'Bitrue World Cup 2026 - $25M Prize Pool',
    description: 'Largest crypto World Cup promotion',
    organization: 'Bitrue Exchange',
    prizeDescription: 'Up to $25 million in cryptocurrency and prizes',
    estimatedValue: '25000000',
    amoeMethod: 'Free account registration (no deposit required)',
    physicalRequirements: 'None',
    endDate: new Date('2026-12-31'),
    source: 'Bitrue Official',
  },
  {
    title: 'Crypto.com World Cup Promotions',
    description: 'World Cup prizes from Crypto.com',
    organization: 'Crypto.com',
    prizeDescription: 'Cryptocurrency rewards, NFTs, cash',
    estimatedValue: '500000',
    amoeMethod: 'Free account entry',
    physicalRequirements: 'None',
    endDate: new Date('2026-12-15'),
    source: 'Crypto.com Official',
  },
  {
    title: 'LBank World Cup - $100M Prize Pool',
    description: 'Major crypto exchange World Cup promotion',
    organization: 'LBank',
    prizeDescription: 'Up to $100 million in cryptocurrency',
    estimatedValue: '100000000',
    amoeMethod: 'Free exchange account',
    physicalRequirements: 'None',
    endDate: new Date('2026-12-31'),
    source: 'LBank Official',
  },
  {
    title: 'Nexo Global World Cup Giveaway',
    description: 'Crypto lending platform World Cup promotion',
    organization: 'Nexo',
    prizeDescription: 'Cryptocurrency and cash prizes',
    estimatedValue: '1000000',
    amoeMethod: 'Free account registration',
    physicalRequirements: 'None',
    endDate: new Date('2026-11-30'),
    source: 'Nexo Official',
  },
  {
    title: 'FIFA Fan Token Rewards & Voting',
    description: 'Earn rewards through FIFA Fan Token voting',
    organization: 'Socios/FIFA',
    prizeDescription: 'Cryptocurrency rewards, exclusive access',
    estimatedValue: '5000',
    amoeMethod: 'Free token holdings (no purchase required)',
    physicalRequirements: 'None',
    endDate: new Date('2026-12-31'),
    source: 'Socios Official',
  },

  // Sports Betting
  {
    title: 'DraftKings World Cup Betting Promotions',
    description: 'Betting promotions and prize pools',
    organization: 'DraftKings',
    prizeDescription: 'Cash prizes, bonus credits, merchandise',
    estimatedValue: '50000',
    amoeMethod: 'Free tournament entry available',
    physicalRequirements: 'None',
    endDate: new Date('2026-12-18'),
    source: 'DraftKings Official',
  },
  {
    title: 'FanDuel World Cup Fantasy League',
    description: 'Free fantasy World Cup competition',
    organization: 'FanDuel',
    prizeDescription: 'Cash and prize pool competitions',
    estimatedValue: '100000',
    amoeMethod: 'Free league creation (no betting required)',
    physicalRequirements: 'None',
    endDate: new Date('2026-12-15'),
    source: 'FanDuel Official',
  },
  {
    title: 'ESPN+ World Cup Fantasy Contest',
    description: 'Free ESPN+ World Cup fantasy game',
    organization: 'ESPN',
    prizeDescription: 'Prize pool and merchandise',
    estimatedValue: '10000',
    amoeMethod: 'Free ESPN+ trial eligible',
    physicalRequirements: 'None',
    endDate: new Date('2026-12-20'),
    source: 'ESPN+ Official',
  },

  // International Programs
  {
    title: 'Canadian Airlines World Cup Experience',
    description: 'Air Canada World Cup prize package',
    organization: 'Air Canada',
    prizeDescription: 'Flights, accommodation, match tickets',
    estimatedValue: '10000',
    amoeMethod: 'Mail-in entry (no booking required)',
    physicalRequirements: 'Mail entry to Air Canada address',
    endDate: new Date('2026-11-20'),
    source: 'Air Canada Official',
  },
  {
    title: 'Tourism Australia World Cup Campaign',
    description: 'Australian tourism World Cup sweepstakes',
    organization: 'Tourism Australia',
    prizeDescription: 'Australia trip, World Cup tour packages',
    estimatedValue: '12000',
    amoeMethod: 'Online no-purchase entry',
    physicalRequirements: 'None',
    endDate: new Date('2026-10-31'),
    source: 'Tourism Australia Official',
  },
  {
    title: 'Visit Mexico World Cup Promotion',
    description: 'Mexican tourism World Cup sweepstakes',
    organization: 'Visit Mexico',
    prizeDescription: 'Mexico resort packages, World Cup gear',
    estimatedValue: '8000',
    amoeMethod: 'Online AMOE entry',
    physicalRequirements: 'None',
    endDate: new Date('2026-11-01'),
    source: 'Visit Mexico Official',
  },
  {
    title: 'Tourism New Zealand World Cup',
    description: 'New Zealand tourism World Cup contest',
    organization: 'Tourism New Zealand',
    prizeDescription: 'New Zealand trip, World Cup experience',
    estimatedValue: '9000',
    amoeMethod: 'Free online entry',
    physicalRequirements: 'None',
    endDate: new Date('2026-10-15'),
    source: 'Tourism New Zealand Official',
  },

  // Streaming & Tech
  {
    title: 'Peacock World Cup Free Streaming Sweepstakes',
    description: 'Win premium Peacock access and World Cup gear',
    organization: 'NBCUniversal/Peacock',
    prizeDescription: 'Premium Peacock access, World Cup merchandise',
    estimatedValue: '2000',
    amoeMethod: 'Free Peacock account entry',
    physicalRequirements: 'None',
    endDate: new Date('2026-12-15'),
    source: 'Peacock Official',
  },
  {
    title: 'Telemundo World Cup Contest',
    description: 'Spanish language broadcaster contest',
    organization: 'Telemundo/NBCUniversal',
    prizeDescription: 'World Cup merchandise, experiences',
    estimatedValue: '5000',
    amoeMethod: 'Online entry (no subscription needed)',
    physicalRequirements: 'None',
    endDate: new Date('2026-11-30'),
    source: 'Telemundo Official',
  },
];
